wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.15
    start_time: 1678372109.073928
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      - 37
      4: 3.9.15
      5: 0.13.9
      8:
      - 2
      - 3
      - 5
change_order:
  desc: null
  value: 0
dataset:
  desc: null
  value: Aminer
format:
  desc: null
  value: GraphML
method:
  desc: null
  value: one_shot
self_augument:
  desc: null
  value: 0
task:
  desc: null
  value: degree
